baseURL = 'https://tategotoazarasi.github.io/'
languageCode = 'zh-cn'
title = 'Harp Seal Pup Nursery and Caring Center'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "azarasi"
  description = "ç«–ç´æµ·è±¹å¹¼å´½çˆ±å¥½è€…"
  github = "tategotoazarasi"
  #facebook = "MeiK2333"
  #twitter = "MeiK2333"
  #linkedin = "MeiK2333"
  #instagram = "MeiK2333"
  #tumblr = "MeiK2333"
  email = "2724167997@qq.com"
  url = "https://tategotoazarasi.github.io"
  #keywords = "blog, google analytics"
  rss = true
  lastmod = true
  #userStatusEmoji = "ğŸ˜€"
  favicon = "/images/github.png"
  avatar = "/images/myavatar.webp"
  headerIcon = "/images/github.png"
  location = "China"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
